[package]
name = "lingui_macro_plugin"
version = "4.0.0-next.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
# This removes more dead code
codegen-units = 1
lto = true
# Optimize for size
opt-level = "s"
# Optimize for performance, this is default so you don't need to specify it
# opt-level = "z"

[dependencies]
data-encoding = "2.3.3"
sha2 = "0.10.6"
serde = "1.0.158"
serde_json = "1.0.94"
regex = "1.7.0"
once_cell = "1.17.1"


[target.'cfg(swc_core_069)'.dependencies]
swc_core = { version = "0.69.30", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }

[target.'cfg(swc_core_059)'.dependencies]
swc_core = { version = "0.59.0", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }

[dev-dependencies]
swc_core = {version = "0.72.0", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",

  "testing_transform",
  "ecma_parser",
] }
# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
